name: Deploy Docs

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Tag Version
        id: get_tag_version
        run: echo "::set-output name=tag_version::${{ github.ref_name }}"

      - name: Check Tag Version
        run: |
          if [[ "${{ steps.get_tag_version.outputs.tag_version }}" < "v1.0.0" ]]; then
            echo "Tag version is below v1.0.0. Exiting workflow."
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install deps & Build
        run: pnpm i --frozen-lockfile && pnpm run docs:build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: docs
